CREATE TABLE widget
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    imageurl    VARCHAR(255),
    name        VARCHAR(255),
    description VARCHAR(255),
    price       DOUBLE PRECISION,
    rating      DOUBLE PRECISION,
    CONSTRAINT pk_widget PRIMARY KEY (id)
);
