spring:
  application:
    name: capstone_2

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB:brightforge}
    username: ${POSTGRES_USERNAME:ch10dev}
    password: ${POSTGRES_PASSWORD:ch10dev!}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080